// hello world actions
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_END = 'HELLO_WORLD_END';
// auth actions
export const INIT_AUTH = 'INIT_AUTH';
export const INIT_AUTH_SUCCESS = 'INIT_AUTH_SUCCESS';
export const DO_LOGIN = 'DO_LOGIN';
export const DO_GITHUB_LOGIN = 'DO_GITHUB_LOGIN';
export const DO_GOOGLE_LOGIN = 'DO_GOOGLE_LOGIN';
export const DO_LOGOUT = 'DO_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// notifications actions
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const REMOVE_NOTIFICATION_BY_REF = 'REMOVE_NOTIFICATION_BY_REF';
// comics actions
export const CREATE_COMIC = 'CREATE_COMIC';
export const CREATE_COMIC_SUCCESS = 'CREATE_COMIC_SUCCESS';
export const CREATE_COMIC_ERROR = 'CREATE_COMIC_ERROR';
export const GET_ALL_COMICS = 'GET_ALL_COMICS';
export const GET_ALL_COMICS_SUCCESS = 'GET_ALL_COMICS_SUCCESS';
export const GET_ALL_COMICS_ERROR = 'GET_ALL_COMICS_ERROR';
export const DELETE_COMIC = 'DELETE_COMIC';
export const DELETE_COMIC_SUCCESS = 'DELETE_COMIC_SUCCESS';
export const DELETE_COMIC_ERROR = 'DELETE_COMIC_ERROR';

// observable actions
export const ADD_OBSERVABLE = 'ADD_OBSERVABLE';
export const REMOVE_OBSERVABLE = 'REMOVE_OBSERVABLE';
// Websocket actions
export const OPEN_WEBSOCKET_CONN = 'OPEN_WEBSOCKET_CONN';
export const CLOSE_WEBSOCKET_CONN = 'CLOSE_WEBSOCKET_CONN';
